// ─── Deliverability Service Facade ─────────────────────────────
// Re-exports the unified DeliverabilityService instance and readiness contracts

export {
  DeliverabilityService,
  assertReadyToSend,
  evaluateSendReadiness,
  checkPreSendGuards,
  isResendConfigured,
  checkDomainDnsStatus,
  getWarmupStatus,
  canSendMore,
  getWarmupSchedule,
  calculateReputation,
  getReputationTrend,
  handleBounce,
  handleUnsubscribe,
  classifyBounce,
  addTrackingToHtml,
  textToHtml,
  handleTrackedOpen,
  handleTrackedClick,
  scheduleSends,
  isInSendWindow,
  getOptimalSendTime,
  MIN_SEND_INTERVAL_MS,
  type SendResult,
  type DomainSetupResult,
  type SendReadinessCheck,
  type SendReadinessResult,
  type DomainDnsStatus,
  type DnsRecordStatus,
  type WarmupStatus,
  type ReputationScore,
  type BounceEvent,
  type BounceClassification,
} from './index';
